### ISSUE TITLE
small suggestion

### ISSUE THREAD

**Issue by jonschlinkert** [wooorm/f-ck#1]
Great idea!

Perhaps you should change the description to "clean up cuss words", "sanitize cuss words", "cleanse cuss words", "passify cuss words" etc. 

My initial reaction was that this would be a list of "clean cuss words". Again, small thing, but thought I'd mention it. thanks!

**Comment by wooorm** [comment]
Smart! :)

**Comment by wooorm** [comment]
Thanks!

**Comment by jonschlinkert** [comment]
@wooorm any interest on collaborating on an open source project? I'd like to create a bot that scans new GitHub issues and comments for words or phrases that violate the project's CoC, or specific "rules" for the project. it would then "flag" and potentially close and/or delete comments (replace them with a notice while the comment is emailed to the maintainers for review), etc.  

I could use your skills with the "language" related code. parsing/detecting things that violate the rules :) any interest? this is very much an idea right now, we have bots running already, so we have a codebase to start with, but there is absolutely not pressure or any need for a commitment on this. I just think it sounds fun and is needed

**Comment by wooorm** [comment]
Sure, thanks, that sounds cool!

Do you have ideas for patterns to search for? What’s running already? Could you send me in an email?

**Comment by jonschlinkert** [comment]
> Do you have ideas for patterns to search for?

none! lol that's why I thought you'd make a great collaborator with @doowb and I on this. 

> Could you send me in an email?

absolutely!
